package com.example.scanlearn.utils

object AppConstants {
    const val EXTRA_MODE = "extra_mode"
    const val EXTRA_OBJECT_ID = "extra_object_id"
    const val EXTRA_OBJECT_NAME = "extra_object_name"
    const val EXTRA_OBJECT_STATUS = "extra_object_status"
    const val EXTRA_SCORE = "extra_score"
    const val EXTRA_TOTAL = "extra_total"
    const val EXTRA_HAS_SCANNED_IMAGE = "extra_has_scanned_image"
    const val EXTRA_SCAN_CONFIDENCE = "extra_scan_confidence"
    const val EXTRA_SCAN_CATEGORY = "extra_scan_category"
    const val EXTRA_SCAN_SUGGESTIONS = "extra_scan_suggestions"
    const val EXTRA_SCAN_ATTEMPT_ID = "extra_scan_attempt_id"
    const val EXTRA_SCAN_MANUAL_CORRECTION = "extra_scan_manual_correction"
    const val EXTRA_SCAN_SELECTION_APPLIED = "extra_scan_selection_applied"
    const val EXTRA_SCAN_SELECTION_BOX = "extra_scan_selection_box"
    const val EXTRA_QUIZ_ATTEMPT_ID = "extra_quiz_attempt_id"
    const val EXTRA_STUDENT_PROGRESS = "extra_student_progress"
    const val EXTRA_MISSION_ID = "extra_mission_id"
    const val EXTRA_MISSION_TITLE = "extra_mission_title"
    const val EXTRA_UNIT_ID = "extra_unit_id"
    const val EXTRA_UNIT_TITLE = "extra_unit_title"
    const val EXTRA_LESSON_ID = "extra_lesson_id"
    const val EXTRA_QUARTER_ID = "extra_quarter_id"
    const val EXTRA_QUARTER_TITLE = "extra_quarter_title"
    const val EXTRA_ASSESSMENT_ONLY = "extra_assessment_only"
    const val EXTRA_TEACHER_OBJECT_ID = "extra_teacher_object_id"
    const val EXTRA_CHAT_PARTNER_ID = "extra_chat_partner_id"
    const val EXTRA_CHAT_PARTNER_NAME = "extra_chat_partner_name"
    const val EXTRA_CHAT_PARTNER_ROLE = "extra_chat_partner_role"
    const val MODE_EXPLORER = "explorer"
    const val MODE_MISSION = "mission"
    const val MODE_CHALLENGE = "challenge"
    const val MODE_TEST_KNOWLEDGE = "test_knowledge"
    const val MODE_LEARNING_PLAN = "learning_plan"
}
